apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-access
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: availability-access
  template:
    metadata:
      labels:
        app: availability-access
    spec:
      containers:
      - name: availability-access
        image: olexoi/node2:latest
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80